//Import all widgets
require("./empty")
require("./metricValue")
require("./speedometer")
require("./temperature")
require("./battery")
require("./SOC")
require("./fuel")
require("./gear")
require("./tachometer")
require("./oilPressure")